-- TODO: Fill in these
-- bibkey_completion = function(arglead, cmdline, cursorpos)
--   local keys = {}
--   for line in io.lines("/path/to/your.bib") do
--     local key = line:match("@%w+{(.-),")
--     if key and key:match("^" .. arglead) then
--       table.insert(keys, key)
--     end
--   end
--   return keys
-- end
--
-- _G.jsonkey_completion = function(arglead, cmdline, cursorpos)
--   local json = vim.fn.json_decode(vim.fn.readfile("/path/to/your.json"))
--   local keys = {}
--   for k, _ in pairs(json) do
--     if k:match("^" .. arglead) then
--       table.insert(keys, k)
--     end
--   end
--   return keys
-- end
--
-- local key = vim.fn.input("Enter key: ", "", "customlist,v:lua.jsonkey_completion")
